#!/usr/bin/env python3
"""Generates engines/igor/parts/part_maze_data.cpp (and the resource catalog rows) of the maze rooms, parts 51..66,
from the DOS disassembly with tools/maze_asm.py. Usage: gen_maze_data.py <fork igor dir> [--apply-resources]"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from maze_asm import *

FORK = sys.argv[1]
PARTS = list(range(51, 68))
FRAMES = {"flame103": "kMazeFlameFixed", "flame107": "kMazeFlameFirstFrame", "flame108": "kMazeFlameLayer1"}
FACING = {1: "kFacingPositionBack", 2: "kFacingPositionRight", 3: "kFacingPositionFront", 4: "kFacingPositionLeft"}


def main():
	exe, nseg = ne_segments()
	base, size = nseg(231)
	ds = exe[base:base + size]
	nodes = [tuple(ds[5421 + i * 5:5421 + i * 5 + 5]) for i in range(108)]
	rooms = {p: parse_room(p) for p in PARTS}

	# resources: the picture sets are shared by the rooms of the same loader
	sets = {}
	for p in PARTS:
		r = rooms[p]
		key = r["info"]["loader"]
		sets.setdefault(key, []).append(p)
	setNames = {}
	for key, parts in sets.items():
		setNames[key] = "MazeEntrance" if 67 in parts else "Maze%d" % parts[0]
	resources = []   # (name, offset, size)
	ids = {}
	nextId = 998
	idsOf = {}

	def addRes(kind, name, off, size):
		global_ = None
		return None
	order = ["TXT", "IMG", "PAL", "MSK", "BOX"]
	done = set()
	rows = []
	for p in PARTS:
		r = rooms[p]
		loader = r["info"]["loader"]
		idsOf[p] = {}
		off, sz = r["res"]["DAT"]
		name = "DAT_Maze%d" % p
		if p == 67:
			name = "DAT_MazeEntrance"   # already in the table
		else:
			rows.append((name, nextId, off, sz))
			nextId += 1
		idsOf[p]["DAT"] = name
		if loader not in done:
			done.add(loader)
			for k in order:
				off, sz = r["res"][k]
				name = "%s_%s" % (k, setNames[loader])
				if setNames[loader] == "MazeEntrance":
					continue
				rows.append((name, nextId, off, sz))
				nextId += 1
		for k in order:
			idsOf[p][k] = "%s_%s" % (k, setNames[loader])
	return rooms, nodes, rows, idsOf, setNames


def cpp(rooms, nodes, idsOf):
	out = []
	w = out.append
	w("""/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_maze_data.py from the disassembly of the maze rooms. Do not edit.

#include "igor/igor.h"

namespace Igor {

#define MAZE_EXIT(code, x1, y1, x2, y2, dir) { code, kMazeActionExit, x1, y1, x2, y2, dir, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
#define MAZE_STAIRS_EXIT(code, x, dir) { code, kMazeActionStairsExit, 0, 0, 0, 0, dir, x, 0, 0, 0, 0, 0, 0, 0, 0 }
#define MAZE_EXIT_FIXED(code, x1, y1, x2, y2, location, state, objectState, objectStateValue) \
	{ code, kMazeActionExitFixed, x1, y1, x2, y2, 0, 0, location, state, objectState, objectStateValue, 0, 0, 0, 0 }
#define MAZE_DIALOGUE(code, lines, count, start, shown) { code, kMazeActionDialogue, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, lines, count, start, shown }
""")
	w("// The maze is a grid of locations. For each one: the locations to the north, east, south and west (0: none)")
	w("// and the shape of the room that shows it (the part is 50 + shape).")
	w("const MazeNode IgorEngine::MAZE_NODES[%d] = {" % len(nodes))
	for i, n in enumerate(nodes):
		w("\t{ { %d, %d, %d, %d }, %d }%s // %d" % (n[0], n[1], n[2], n[3], n[4], "," if i < len(nodes) - 1 else "", i))
	w("};\n")
	# room data offsets, shared
	offs = {}
	for p, r in rooms.items():
		o = r["offsets"]
		key = (o["walk"], o["facing"], o["defaultVerb"], o["use"], o["give"], o["object2"], o["object1"], o["size"])
		offs.setdefault(key, []).append(p)
	offName = {}
	for i, (key, parts) in enumerate(offs.items()):
		offName[key] = "kMazeOffsets%d" % i
		w("// parts %s" % ", ".join(map(str, parts)))
		w("static const RoomDataOffsets %s = {" % offName[key])
		w("\t{ 0, 0, 0, 0 },")
		w("\t{ %d, %d }," % (key[0], key[1]))
		w("\t{ %d, %d, %d, %d, %d, %d }," % (key[2], key[3], key[4], key[5], key[6], key[7]))
		w("\t{ 0, 0, 0, 0, 0, 0, 0, 0, 0 }")
		w("};\n")
	roomLines = []
	for p, r in rooms.items():
		pre = "kMaze%d" % p
		ent = r["entries"]
		states = [e[0] if e[0] else r["loopStates"][0] for e in ent]
		assert states == r["loopStates"], (p, states, r["loopStates"])
		w("static const MazeEntry %sEntries[] = {" % pre)
		for st, (state, kind, e) in zip(states, ent):
			if kind == "walk":
				w("\t{ %d, kMazeEntryWalk, %d, %d, %s, %d, %d }," % (st, e["x"], e["y"], FACING[e["facing"]], e["x2"], e["y2"]))
			else:
				w("\t{ %d, kMazeEntryStairs, %d, 0, 0, 0, 0 }," % (st, e["x"]))
		w("};\n")
		# dialogues
		lines = []
		w_actions = []
		for code, (kind, a) in r["actions"].items():
			if kind == "dialogue":
				var = "%sLines%d" % (pre, code)
				w("static const MazeDialogueLine %s[] = {" % var)
				for (t, c, s) in a["lines"]:
					w("\t{ %d, %d, %d }," % (t, c, s))
				w("};")
				w_actions.append("\tMAZE_DIALOGUE(%d, %s, %d, %d, %d)," % (code, var, len(a["lines"]), a["start"], a["count"]))
			elif kind == "exit":
				w_actions.append("\tMAZE_EXIT(%d, %d, %d, %d, %d, %d)," % (code, a["x1"], a["y1"], a["x2"], a["y2"], a["dir"]))
			elif kind == "stairsExit":
				w_actions.append("\tMAZE_STAIRS_EXIT(%d, %d, %d)," % (code, a["x"], a["dir"]))
			elif kind == "exitFixed":
				os_ = a["objectState"]
				w_actions.append("\tMAZE_EXIT_FIXED(%d, %d, %d, %d, %d, %d, %d, %d, %d)," % (
					code, a["x1"], a["y1"], a["x2"], a["y2"], -1 if a["location"] is None else a["location"], a["state"],
					-1 if os_ is None else os_[0], 0 if os_ is None else os_[1]))
			else:
				raise Exception((p, code, kind))
		w("static const MazeAction %sActions[] = {" % pre)
		for l in w_actions:
			w(l)
		w("};\n")
		roomLines.append(p)
	w("static const MazeRoom kMazeRooms[] = {")
	for p in roomLines:
		r = rooms[p]
		pre = "kMaze%d" % p
		o = r["offsets"]
		key = (o["walk"], o["facing"], o["defaultVerb"], o["use"], o["give"], o["object2"], o["object1"], o["size"])
		fl = r["flameFns"]
		mode = FRAMES[fl[0]] if fl else "kMazeFlameNone"
		# flames: positions and initial frames
		init = r["flameInit"]
		flames = []
		if fl and fl[0] == "flame103":
			flames = [(81, 52, 0)]
		elif fl:
			flames = [(c[1], c[2], c[0]) for c in init]
		c2 = r["eb2d"][0] if r["eb2d"] else 0
		click = r["clickfix"]
		music = r["info"]["music"]
		w("\t{ %d, %s, %s, %s, %s, %s, %s, %d, %d, %s, %d," % (
			p, idsOf[p]["DAT"], idsOf[p]["TXT"], idsOf[p]["IMG"], idsOf[p]["PAL"], idsOf[p]["MSK"], idsOf[p]["BOX"],
			-1 if music == "location" else music, r["info"]["darkness"], mode, len(flames)))
		fs = ", ".join("{ %d, %d }" % (f[0], f[1]) for f in flames) if flames else ""
		w("\t  { %s }, { %s }, %d," % (fs, ", ".join(str(f[2]) for f in flames), c2))
		w("\t  %s, &%s, %d," % ("true" if r["saveLocation"] else "false", offName[key], o["giveSize"] if o["giveSize"] != o["size"] else 0))
		w("\t  { %d, %s, %s, %s, false }," % (click["yMax"], "-1" if click["xMin"] is None else click["xMin"], "-1" if click["xMax"] is None else click["xMax"], "true" if click["scanUp"] else "false"))
		w("\t  %sEntries, %d, %sActions, %d, %s }%s" % (pre, len(r["entries"]), pre, len(r["actions"]), '" esqueleto"' if p == 66 else "0", "," if p != roomLines[-1] else ""))
	w("};\n")
	w("""const MazeRoom *IgorEngine::getMazeRoom(int part) {
	for (int i = 0; i < ARRAYSIZE(kMazeRooms); ++i) {
		if (kMazeRooms[i].part == part) {
			return &kMazeRooms[i];
		}
	}
	return 0;
}
""")
	w("} // End of namespace Igor")
	return "\n".join(out) + "\n"


def patch(path, begin, end, lines, anchor_after=None, anchor_before=None, encoding="utf-8"):
	text = open(path, encoding=encoding).read()
	block = begin + "\n" + "\n".join(lines) + "\n" + end + "\n"
	if begin in text:
		a = text.index(begin)
		b = text.index(end) + len(end) + 1
		text = text[:a] + block + text[b:]
	elif anchor_after:
		i = text.index(anchor_after)
		i = text.index("\n", i) + 1
		text = text[:i] + block + text[i:]
	else:
		i = text.index(anchor_before)
		text = text[:i] + block + text[i:]
	open(path, "w", encoding=encoding).write(text)


def apply_resources(rows):
	tool = os.path.join(ROOT, "reference", "scummvm-create-igortbl")
	for name in ("resource_sp_cdrom.h", "resource_ids_extra.h"):
		p = os.path.join(tool, name)
		t = open(p, encoding="latin-1").read().replace("UndergroundCorridor", "MazeEntrance")
		open(p, "w", encoding="latin-1").write(t)
	patch(os.path.join(tool, "resource_ids_extra.h"), "// MAZE ROOMS BEGIN", "// MAZE ROOMS END",
	      ["#define %s %d" % (n, i) for n, i, o, z in rows], anchor_after="#define BOX_MazeEntrance", encoding="latin-1")
	patch(os.path.join(tool, "resource_sp_cdrom.h"), "// MAZE ROOMS BEGIN", "// MAZE ROOMS END",
	      ["{ %s, 0x%x, %d }," % (n, o, z) for n, i, o, z in rows], anchor_after="{ BOX_MazeEntrance", encoding="latin-1")
	patch(os.path.join(FORK, "resource_ids.h"), "// MAZE ROOMS BEGIN", "// MAZE ROOMS END",
	      ["#define %s %d // IGOR.EXE:0x%X, 0x%04X bytes" % (n, i, o, z) for n, i, o, z in rows], anchor_after="#define BOX_MazeEntrance")


if __name__ == "__main__":
	rooms, nodes, rows, idsOf, setNames = main()
	text = cpp(rooms, nodes, idsOf)
	open(os.path.join(FORK, "parts", "part_maze_data.cpp"), "w").write(text)
	if "--apply-resources" in sys.argv:
		apply_resources(rows)
	print("%d resources, ids %d..%d" % (len(rows), rows[0][1], rows[-1][1]))
