/* Resource ids absent from the historical 2009 header. These must match the
 * active fork's engines/igor/resource_ids.h. */
#define PAL_OutsideAdministrationBuildingA 900
#define IMG_OutsideAdministrationBuildingA 901
#define MSK_OutsideAdministrationBuildingA 902
#define BOX_OutsideAdministrationBuildingA 903
#define PAL_OutsideAdministrationBuildingB 904
#define IMG_OutsideAdministrationBuildingB 905
#define MSK_OutsideAdministrationBuildingB 906
#define BOX_OutsideAdministrationBuildingB 907
#define TXT_OutsideAdministrationBuildingA 908
#define TXT_OutsideAdministrationBuildingB 909
#define WLK_OutsideAdministrationBuildingA 910
#define WLK_OutsideAdministrationBuildingB 911
#define DAT_OutsideAdministrationBuildingPart11 912
#define FRM_IgorIntroLogo 913
#define IMG_IgorIntroLogo 914
#define PAL_IgorIntroLogo 915
#define DAT_AdministrationCorridor 916
#define ANM_AdministrationCorridor 917
#define TXT_AdministrationCorridor 918
#define IMG_AdministrationCorridor 919
#define PAL_AdministrationCorridor 920
#define MSK_AdministrationCorridor 921
#define BOX_AdministrationCorridor 922
#define ANM_AdministrationSecretaryRoom1 923
#define ANM_AdministrationSecretaryRoom2 924
#define ANM_AdministrationSecretaryRoom3 925
#define ANM_AdministrationSecretaryRoom4 926
#define ANM_AdministrationSecretaryRoom5 927
#define ANM_AdministrationSecretaryRoom6 928
#define ANM_AdministrationSecretaryRoom7 929
#define ANM_AdministrationSecretaryRoom8 930
#define ANM_AdministrationSecretaryRoom9 931
#define ANM_DecanatoHamburger 932
