{ STR_Copyright1995, STR_LANG_ANY, "(C) 1995 Optik Software. All rights reserved." },
{ STR_Copyright1994, STR_LANG_ANY, "(C) 1994 PENDULO STUDIOS. All rights reserved." },

{ STR_BottleOfWhisky, STR_LANG_ENG, " bottle of whisky" },
{ STR_EmptyBottle, STR_LANG_ENG, " empty bottle" },
{ STR_BottleOfWater, STR_LANG_ENG, " bottle of water" },
{ STR_Lizard, STR_LANG_ENG, " lizard" },
{ STR_FatLizard, STR_LANG_ENG, " fat lizard" },
{ STR_CarolineFolder, STR_LANG_ENG, " Caroline%s folder" },
{ STR_PhilipFolder, STR_LANG_ENG, " Philip%s folder" },
{ STR_Statuette, STR_LANG_ENG, " statuette" },
{ STR_Reward, STR_LANG_ENG, " reward" },

{ STR_BottleOfWhisky, STR_LANG_SPA, " botella de whisky" },
{ STR_EmptyBottle, STR_LANG_SPA, " botella vac¡a" },
{ STR_BottleOfWater, STR_LANG_SPA, " botella con agua" },
{ STR_Lizard, STR_LANG_SPA, " lagarto" },
{ STR_FatLizard, STR_LANG_SPA, " lagarto cebado" },
{ STR_CarolineFolder, STR_LANG_SPA, " carpeta de Caroline" },
{ STR_PhilipFolder, STR_LANG_SPA, " carpeta de Philip" },
{ STR_Statuette, STR_LANG_SPA, " estatuilla" },
{ STR_Reward, STR_LANG_SPA, " recompensa" },
{ STR_ShinyThing, STR_LANG_SPA, " cosa reluciente" },

{ STR_Talk, STR_LANG_SPA, "Hablar" },
{ STR_Take, STR_LANG_SPA, "Coger" },
{ STR_Look, STR_LANG_SPA, "Mirar" },
{ STR_Use, STR_LANG_SPA, "Usar" },
{ STR_Open, STR_LANG_SPA, "Abrir" },
{ STR_Close, STR_LANG_SPA, "Cerrar" },
{ STR_Give, STR_LANG_SPA, "Dar" },

{ STR_PushStone, STR_LANG_SPA, "Empujar piedra" },
{ STR_Exit, STR_LANG_SPA, "Salir" },

{ STR_PushStone, STR_LANG_ENG, "Push stone" },
{ STR_Exit, STR_LANG_ENG, "Exit" },

{ STR_GamePaused, STR_LANG_ENG, "GAME PAUSED" },

{ STR_IgorObjectiveUikokahonia, STR_LANG_ENG, "\"Igor. Objective Uikokahonia\"" },
{ STR_SharewareVersion, STR_LANG_ENG, "Shareware version" },
{ STR_SharewarePlaceOrder, STR_LANG_ENG, "To place an order: 1-800-OPTIK-99" },

{ STR_SharewareText1, STR_LANG_ENG, "This is SHAREWARE!" },
{ STR_SharewareText2, STR_LANG_ENG, "You can copy this version!" },
{ STR_SharewareText3, STR_LANG_ENG, "Pass it around, give it to your friends, family," },
{ STR_SharewareText4, STR_LANG_ENG, "colleagues and upload it to your favorite BBS." },
{ STR_SharewareText5, STR_LANG_ENG, "Let everyone enjoy IGOR!" },

{ STR_SharewareOrder1, STR_LANG_ENG, "Order the full IGOR game for only $34.99 US." },
{ STR_SharewareOrder2, STR_LANG_ENG, "$5.00 for shipping and handling (US & CANADA)." },
{ STR_SharewareOrder3, STR_LANG_ENG, "Please add $3.00 for international shipping." },
{ STR_SharewareOrder4, STR_LANG_ENG, "To place an order: 1-800-OPTIK-99" },

{ STR_SharewareShipping1, STR_LANG_ENG, "90 day limited warranty." },
{ STR_SharewareShipping2, STR_LANG_ENG, "Please allow 2-4 days for delivery (US only)." },
{ STR_SharewareShipping3, STR_LANG_ENG, "Elsewhere, up to a week or two..." },
{ STR_SharewareShipping4, STR_LANG_ENG, "Overnight/second day shipping available an" },
{ STR_SharewareShipping5, STR_LANG_ENG, "aditional change. Please call for exact pricing." },
{ STR_SharewareShipping6, STR_LANG_ENG, "Three easy ways to order:" },
{ STR_SharewareShipping7, STR_LANG_ENG, "- Call 1-800-678-4599 (orders only) and use" },
{ STR_SharewareShipping8, STR_LANG_ENG, "Your Visa, Mastercard or Discover card." },
{ STR_SharewareShipping9, STR_LANG_ENG, "- Fax your order (please include credit card" },
{ STR_SharewareShipping10, STR_LANG_ENG, "information) to (412) 381-1031" },

{ STR_SharewareOptikAddress1, STR_LANG_ENG, "- Mail a check or money order to:" },
{ STR_SharewareOptikAddress2, STR_LANG_ENG, "Optik Software Inc." },
{ STR_SharewareOptikAddress3, STR_LANG_ENG, "1000 Napor Boulevard" },
{ STR_SharewareOptikAddress4, STR_LANG_ENG, "Pittsburgh, PA. 15205" },
{ STR_SharewareOptikAddress5, STR_LANG_ENG, "USA" },
{ STR_SharewareOptikAddress6, STR_LANG_ENG, "Optik Software Inc." },
{ STR_SharewareOptikAddress7, STR_LANG_ENG, "Orders only: 1-800-OPTIK-99 (67845-99)" },
{ STR_SharewareOptikAddress8, STR_LANG_ENG, "Fax: (412) 381-1031" },
{ STR_SharewareOptikAddress9, STR_LANG_ENG, "E-mail: optiksoft\xFA""aol.com" },

{ STR_SharewarePenduloAddress1, STR_LANG_ENG, "A game by" },
{ STR_SharewarePenduloAddress2, STR_LANG_ENG, "PENDULO STUDIOS" },
{ STR_SharewarePenduloAddress3, STR_LANG_ENG, "P.O. Box 21091" },
{ STR_SharewarePenduloAddress4, STR_LANG_ENG, "28009 Madrid" },
{ STR_SharewarePenduloAddress5, STR_LANG_ENG, "Spain" },
{ STR_SharewarePenduloAddress6, STR_LANG_ENG, "E-mail: 100641.1737\xFA""compuserve.com" },

{ STR_CreditsHistoriaYDiseno, STR_LANG_SPA, "historia y dise\xA4o" },
{ STR_CreditsRamonHernaez, STR_LANG_SPA, "RAMON HERNAEZ" },
{ STR_CreditsFelipeGomez, STR_LANG_SPA, "FELIPE GOMEZ" },
{ STR_CreditsRafaelLatiegui, STR_LANG_SPA, "RAFAEL LATIEGUI" },
{ STR_CreditsMiguelAngelRamos, STR_LANG_SPA, "MIGUEL ANGEL RAMOS" },
{ STR_CreditsProduccionYDireccionDeVoces, STR_LANG_SPA, "producci\xA2n y direcci\xA2n de voces" },
{ STR_CreditsLunaFaraco, STR_LANG_SPA, "LUNA FARACO" },
{ STR_CreditsProgramacion, STR_LANG_SPA, "programaci\xA2n" },
{ STR_CreditsVoces, STR_LANG_SPA, "voces" },
{ STR_CreditsAngieDeBirch, STR_LANG_SPA, "ANGIE DE BIRCH" },
{ STR_CreditsAntonioFdezMunoz, STR_LANG_SPA, "ANTONIO FDEZ. MU\xA5OZ" },
{ STR_CreditsArantxaFranco, STR_LANG_SPA, "ARANTXA FRANCO" },
{ STR_CreditsAlfredoGabrieli, STR_LANG_SPA, "ALFREDO GABRIELI" },
{ STR_CreditsFernandoLuna, STR_LANG_SPA, "FERNANDO LUNA" },
{ STR_CreditsAnaOlivares, STR_LANG_SPA, "ANA OLIVARES" },
{ STR_CreditsAdolfoPastor, STR_LANG_SPA, "ADOLFO PASTOR" },
{ STR_CreditsFondos, STR_LANG_SPA, "fondos" },
{ STR_CreditsCarlosVeredas, STR_LANG_SPA, "CARLOS VEREDAS" },
{ STR_CreditsMiguelAngelPerez, STR_LANG_SPA, "MIGUEL ANGEL PEREZ" },
{ STR_CreditsAntonioRamos, STR_LANG_SPA, "ANTONIO RAMOS" },
{ STR_CreditsPatriciaReija, STR_LANG_SPA, "PATRICIA REIJA" },
{ STR_CreditsAparicioRivero, STR_LANG_SPA, "APARICIO RIVERO" },
{ STR_CreditsDanielSanchez, STR_LANG_SPA, "DANIEL SANCHEZ" },
{ STR_CreditsEnriqueSantaren, STR_LANG_SPA, "ENRIQUE SANTAREN" },
{ STR_CreditsCarlosViaga, STR_LANG_SPA, "CARLOS VIAGA" },
{ STR_CreditsAnimaciones, STR_LANG_SPA, "animaciones" },
{ STR_CreditsProductorAsociado, STR_LANG_SPA, "productor asociado" },
{ STR_CreditsPabloDeLaNuez, STR_LANG_SPA, "PABLO DE LA NUEZ" },
{ STR_CreditsMusicaOriginalYArreglos, STR_LANG_SPA, "m\xA3sica original y arreglos" },
{ STR_CreditsEstebanMoreno, STR_LANG_SPA, "ESTEBAN MORENO" },
{ STR_CreditsDistribuidoPor, STR_LANG_SPA, "distribuido por" },
{ STR_CreditsDinamicMultimedia, STR_LANG_SPA, "DINAMIC MULTIMEDIA" },
{ STR_CreditsProduccionMusicaDigital, STR_LANG_SPA, "producci\xA2n m\xA3sica digital" },
{ STR_CreditsAgpDigital, STR_LANG_SPA, "AGP DIGITAL" },
{ STR_CreditsAgradecimientos, STR_LANG_SPA, "agradecimientos" },
{ STR_CreditsThePromisedLand, STR_LANG_SPA, "THE PROMISED LAND" },
{ STR_CreditsRaquelAlvarez, STR_LANG_SPA, "RAQUEL ALVAREZ" },
{ STR_CreditsPilarRomero, STR_LANG_SPA, "PILAR ROMERO" },
{ STR_CreditsDouglasPrats, STR_LANG_SPA, "DOUGLAS PRATS" },
{ STR_CreditsEnriqueRAtienzar, STR_LANG_SPA, "ENRIQUE R. ATIENZAR" },
{ STR_CreditsEfectosDeSonido, STR_LANG_SPA, "efectos de sonido" },
{ STR_CreditsCreadoYProducidoPor, STR_LANG_SPA, "creado y producido por" },
{ STR_CreditsPenduloStudios, STR_LANG_SPA, "PENDULO STUDIOS" },
